/* Gallery data – add new photos here. file = name in images/gallery & images/thumbs */
window.GALLERY = [
  {file:"cake-001.jpg", cat:"floral", title:"Hand-painted floral buttercream"},
  {file:"cake-002.jpg", cat:"floral", title:"Painted blooms"},
  {file:"cake-003.jpg", cat:"floral", title:"Floral detail"},
  {file:"cake-004.jpg", cat:"kids", title:"Minecraft & pink floral duo"},
  {file:"cake-005.jpg", cat:"kids", title:"Aiden's hot-air balloon 1st"},
  {file:"cake-006.jpg", cat:"kids", title:"Twin birthday cakes"},
  {file:"cake-007.jpg", cat:"kids", title:"Minecraft theme"},
  {file:"cake-008.jpg", cat:"kids", title:"Double celebration"},
  {file:"cake-009.jpg", cat:"kids", title:"Up, up and away"},
  {file:"cake-010.jpg", cat:"kids", title:"Teddy in the balloon"},
  {file:"cake-011.jpg", cat:"kids", title:"Happy Birthday Aiden"},
  {file:"cake-012.jpg", cat:"kids", title:"Two-tier balloon cake"},
  {file:"cake-013.jpg", cat:"kids", title:"Sky-blue first birthday"},
  {file:"cake-014.jpg", cat:"celebration", title:"Ruffle cake at the venue"},
  {file:"cake-015.jpg", cat:"celebration", title:"White ruffle & roses"},
  {file:"cake-016.jpg", cat:"celebration", title:"Ivory ruffle sheet cake"},
  {file:"cake-017.jpg", cat:"celebration", title:"Roses & ruffles"},
  {file:"cake-018.jpg", cat:"floral", title:"Pressed wildflower cake"},
  {file:"cake-019.jpg", cat:"floral", title:"Pressed flowers"},
  {file:"cake-020.jpg", cat:"celebration", title:"Elegant ruffle detail"},
  {file:"cake-021.jpg", cat:"birthday", title:"A table of celebrations"},
  {file:"cake-022.jpg", cat:"birthday", title:"Chocolate drip classic"},
  {file:"cake-023.jpg", cat:"floral", title:"Botanical buttercream"},
  {file:"cake-024.jpg", cat:"birthday", title:"Gold & ivory birthday"},
  {file:"cake-025.jpg", cat:"birthday", title:"Gold spheres & butterflies"},
  {file:"cake-026.jpg", cat:"birthday", title:"Ribbed gold birthday"},
  {file:"cake-027.jpg", cat:"treats", title:"Jam & cream sponge"},
  {file:"cake-028.jpg", cat:"birthday", title:"Jewelled stripes"},
  {file:"cake-029.jpg", cat:"treats", title:"Party slices"},
  {file:"cake-030.jpg", cat:"treats", title:"Victoria sponge squares"},
  {file:"cake-031.jpg", cat:"christening", title:"Abner's christening"},
  {file:"cake-032.jpg", cat:"christening", title:"Angel wings & cross"},
  {file:"cake-033.jpg", cat:"birthday", title:"Rose's 25th with treats"},
  {file:"cake-034.jpg", cat:"treats", title:"Pink portions"},
  {file:"cake-035.jpg", cat:"birthday", title:"Three-tier 25th"},
  {file:"cake-036.jpg", cat:"celebration", title:"Thirty Together"},
  {file:"cake-037.jpg", cat:"celebration", title:"Azulejo & lemons anniversary"},
  {file:"cake-038.jpg", cat:"celebration", title:"Oh Baby shower cake"},
  {file:"cake-039.jpg", cat:"birthday", title:"Happy Birthday Rose"},
  {file:"cake-040.jpg", cat:"celebration", title:"Oh Baby"},
  {file:"cake-041.jpg", cat:"floral", title:"Red roses & pearls"},
  {file:"cake-042.jpg", cat:"treats", title:"Number cakes with berries"},
  {file:"cake-043.jpg", cat:"treats", title:"Chocolate number cakes"},
  {file:"cake-044.jpg", cat:"kids", title:"Toy Story 2nd birthday"},
  {file:"cake-045.jpg", cat:"celebration", title:"Pastel baby shower"},
  {file:"cake-046.jpg", cat:"birthday", title:"Berries & vintage piping"},
  {file:"cake-047.jpg", cat:"treats", title:"Rich chocolate layers"},
  {file:"cake-048.jpg", cat:"kids", title:"To infinity & beyond"},
  {file:"cake-049.jpg", cat:"birthday", title:"Azulejo & lemon Gloria"},
  {file:"cake-050.jpg", cat:"birthday", title:"Portuguese tile design"},
  {file:"cake-051.jpg", cat:"christening", title:"Boho communion"},
  {file:"cake-052.jpg", cat:"floral", title:"Mum bouquet cake"},
  {file:"cake-053.jpg", cat:"celebration", title:"Corporate 50th anniversary"},
  {file:"cake-054.jpg", cat:"birthday", title:"Ocean wave cake"},
  {file:"cake-055.jpg", cat:"birthday", title:"Seaside birthday"},
  {file:"cake-056.jpg", cat:"birthday", title:"Vintage birthday pair"},
  {file:"cake-057.jpg", cat:"birthday", title:"Classic Happy Birthday"},
  {file:"cake-058.jpg", cat:"celebration", title:"Gold & burgundy tiers"},
  {file:"cake-059.jpg", cat:"floral", title:"Floral bouquet for Mum"},
  {file:"cake-060.jpg", cat:"christening", title:"Jace's christening"},
  {file:"cake-061.jpg", cat:"celebration", title:"Goan azulejo heart"},
  {file:"cake-062.jpg", cat:"celebration", title:"Heart & doorway celebration"},
  {file:"cake-063.jpg", cat:"birthday", title:"Fruit-topped birthday"},
  {file:"cake-064.jpg", cat:"christening", title:"Dried-palm communion"},
  {file:"cake-065.jpg", cat:"celebration", title:"Regal gold tiers"},
  {file:"cake-066.jpg", cat:"christening", title:"First Holy Communion"},
  {file:"cake-067.jpg", cat:"kids", title:"Roblox & christening trio"},
  {file:"cake-068.jpg", cat:"christening", title:"Gold cross & peony"},
  {file:"cake-069.jpg", cat:"christening", title:"Draped two-tier"},
  {file:"cake-070.jpg", cat:"birthday", title:"Navy & gold"},
  {file:"cake-071.jpg", cat:"celebration", title:"Floral wedding cake"},
  {file:"cake-072.jpg", cat:"kids", title:"Lego-themed 1st"},
  {file:"cake-073.jpg", cat:"kids", title:"Building-block birthday"},
  {file:"cake-074.jpg", cat:"kids", title:"Little one turns one"},
  {file:"cake-075.jpg", cat:"birthday", title:"Berry heart cake"},
  {file:"cake-076.jpg", cat:"birthday", title:"Music & camera theme"},
  {file:"cake-077.jpg", cat:"christening", title:"Chalice communion tiers"},
  {file:"cake-078.jpg", cat:"birthday", title:"Vintage pastel"},
  {file:"cake-079.jpg", cat:"christening", title:"Tuxedo communion"},
  {file:"cake-080.jpg", cat:"christening", title:"Blue wave communion"},
  {file:"cake-081.jpg", cat:"christening", title:"Communion duo"},
  {file:"cake-082.jpg", cat:"christening", title:"Caydon's Holy Communion"},
  {file:"cake-083.jpg", cat:"christening", title:"Confirmation with pearls"},
  {file:"cake-084.jpg", cat:"kids", title:"My Little Pony tower"},
  {file:"cake-085.jpg", cat:"kids", title:"Princess 5th birthday"},
  {file:"cake-086.jpg", cat:"christening", title:"Snowal's communion"},
  {file:"cake-087.jpg", cat:"treats", title:"Fruit dessert platter"},
  {file:"cake-088.jpg", cat:"treats", title:"Dessert board"},
  {file:"cake-089.jpg", cat:"floral", title:"Pink butterfly duo"},
  {file:"cake-090.jpg", cat:"christening", title:"God Bless"},
  {file:"cake-091.jpg", cat:"treats", title:"Baby-feet cupcakes"},
  {file:"cake-092.jpg", cat:"christening", title:"Caleb's christening"},
  {file:"cake-093.jpg", cat:"birthday", title:"Bows & piping"},
  {file:"cake-094.jpg", cat:"floral", title:"Burgundy sugar flowers"},
  {file:"cake-095.jpg", cat:"kids", title:"Pony party set"},
  {file:"cake-096.jpg", cat:"treats", title:"Rainbow swirl cupcakes"},
  {file:"cake-097.jpg", cat:"birthday", title:"Black & gold drip"},
  {file:"cake-098.jpg", cat:"celebration", title:"Communion & wedding table"},
  {file:"cake-099.jpg", cat:"christening", title:"Chriselle's christening"},
  {file:"cake-100.jpg", cat:"treats", title:"Birthday cupcake box"}
];
